//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaTicketShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArenaDB : DbContext
    {
        public ArenaDB()
            : base("name=ArenaDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blagajna> Blagajna { get; set; }
        public virtual DbSet<Dogadaj> Dogadaj { get; set; }
        public virtual DbSet<Dvorana> Dvorana { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
        public virtual DbSet<Radi_na> Radi_na { get; set; }
        public virtual DbSet<Sektor> Sektor { get; set; }
        public virtual DbSet<Sjedalo> Sjedalo { get; set; }
        public virtual DbSet<Sjedalo_rez> Sjedalo_rez { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }

        public Dogadaj Dogadaj1
        {
            get => default(Dogadaj);
            set
            {
            }
        }
    }
}
