//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaTicketShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogadaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogadaj()
        {
            this.Sjedalo_rez = new HashSet<Sjedalo_rez>();
        }
    
        public int dogadaj_id { get; set; }
        public string naziv_dogadaja { get; set; }
        public System.DateTime vrijeme_dogadaja { get; set; }
        public int dvorana_dvorana_id { get; set; }
        public Nullable<int> cijena { get; set; }
    
        public virtual Dvorana Dvorana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sjedalo_rez> Sjedalo_rez { get; set; }
    }
}
