//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaTicketShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radi_na
    {
        public int radi_na_id { get; set; }
        public int korisnik_korisnik_id { get; set; }
        public int blagajna_blagajna_id { get; set; }
        public System.DateTime pocetak_smjene { get; set; }
        public System.DateTime kraj_smjene { get; set; }
    
        public virtual Blagajna Blagajna { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
