//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaTicketShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sjedalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sjedalo()
        {
            this.Sjedalo_rez = new HashSet<Sjedalo_rez>();
        }
    
        public int sjedalo_id { get; set; }
        public int red { get; set; }
        public int broj { get; set; }
        public int sektor_sektor_id { get; set; }
    
        public virtual Sektor Sektor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sjedalo_rez> Sjedalo_rez { get; set; }
    }
}
